M7R0
I)schubert=6"%&falseGE\[lbo%.additivebasisGf*6#%"XG6,%$invG%"DG%"kG%#RkG%$RDkG%
"AG%"iG%"jG%%rowsG%%colsGF$F$C+@$/9#""!-%'RETURNG6#%8usage:~additivebasis(X)G@$
4-%%typeG6$9$%&tableG-%&ERRORG6#%>Usage:~additivebasis(variety)G@$4-%)assignedG
6#&FD6#%+monomials_G-%*monomialsG6#FD@$4-FM6#&FD6#%0monomialvalues_G-%/monomial
valuesGFT>8%&FD6#%+dimension_G>8&F:?(F$"""F`oF$1F^o,&FinF`oF^o!""C*>8'&FO6#F^o>
8(&FO6#Fbo-%)userinfoG6%"#5%&debugG-%$catG6&%3matrix~dimensions~G-%%nopsG6#Ffo%
$~x~G-Fgp6#Fjo>8)-%&arrayG6#7#-%$seqG6$7#-Fcq6$-%0schubert/lookupG6$FY*&&Ffo6#8
*F`o&Fjo6#8+F`o/Far;F`oFjp/F^r;F`oFfp>8$-&%'linalgG6#.%*transposeG6#-&Fjr6#.%(i
nverseG6#-%3schubert/rankblockG6%F]q.8,.8->&&FD6#%'basis_GFho7#-Fcq6$&Fgo6#&Fis
F]r/F^r;F`o-Fgp6#Fis>&&FD6#%+dualbasis_GF\p-%(convertG6$-&Fjr6#%)multiplyG6$Fgr
-F_q6#7#-Fcq6$&F[p6#&F[tF]r/F^r;F`o-Fgp6#F[t%%listG>F^o,&F^oF`oF`oF`o?(F^oF:F`o
,&Fin#F`o""##FcoFjvF`o%%trueGC$>&F^tF\pF\u>&F]uFhoF]t-Fcp6$%Ca~pair~of~dual~bas
es~computed~for~GFDF$F$F$%$chiGf*F$6%F2F*%"FGF$F$C%@$F8-F<6#%:usage:~chi(F)~or~
chi(X,F)G@'/F9FjvC$>Fin&9"6#F`o>F^o&Fcx6#Fjv/F9F`oC$>Fin%0currentvariety_G>F^oF
bx-FG6#%Bwrong~number~of~arguments.~Usage:G@%5/&Fin6#%&kind_G%2projectivebundle
_G/Fcy%1grassmannbundle_G-Few6$&Fin6#%-basevariety_G-%,lowershriekG6$&Fin6#%3st
ructuremorphism_GF^oC$@$4-FM6#&Fin6#%+toddclass_G-%*toddclassG6#Fin-%)integralG
6$Fin-%$addG6$*&-%&coeffG6%&Fin6#.F[[l%"tGFgrF`o-Fg[l6%F^oF\\l,&&Fin6#.F\oF`oFg
rFcoF`o/Fgr;F:F`\lF$F$F$%%downGf*6#%"fGF$F$F$C%@$F8-F<6#%/usage:~down(f)G@'-FM6
#&FD6#%(target_G-%+setvarietyGF`]l-FM6#&FD6#%/basedimension_G>%$DIMGFh]l-FG6#%/
wrong~argumentG-%&whereGF$F$6#F\^lF$%(varietyGf*6*F*%"aG%"bG%"cG%"dG%"eGFh\l%"g
G6$%$optG%$strGF$F$C+@$F8-F<6#%?usage:~variety(name,<options>)G@$4-FB6$FD%%name
G-FG6#%7first~arg~must~be~nameG>FD-FEF$?&Fgr7#&Fcx6#;FjvF9F\w@$-FB6$Fgr%"=GC$>F
in-%*substringG6$-%#opG6$F`oFgr;F`o""$@.3/Fin.%$dimG-FB6$-F]al6$FjvFgr%(integer
G>FjnFhal3/Fin.%$varG-FB6$FhalFdv>&FD6#%+variables_GFhal3/Fin.%$degGF`bl>&FD6#%
)degrees_GFhal3/Fin.%$relGF`bl>&FD6#%+relations_GFhal/Fin.%$poiG>&FD6#%'point_G
Fhal/Fin.%$tanG>&FD6#%/tangentbundle_GFhal@$4-FM6#Fjn>FjnF\^l@$-FM6#FcclFfn@$4-
FB6$&Fcx6#F9Ff`lC$>Fin-Fj`l6$F`elF_al@$5/Fin.%$basG/Fin.%$allG-F'FT-Fe]lFTF`^lF
$F$F$%&adamsGf*6$F.F1F$F$F$C$@$F8-F<6#%2usage:~adams(k,A)G-%%subsG6$/F\\l*&FDF`
oF\\lF`o9%F$F$F$%&segreGf*F$6$Fh^lF.F$F$C$@$F8-F<6#%Nusage:~segre(A)~or~segre(p
,A)~or~segre(p,q,A)G@)Fhx-%.schubert/exppG6#,$-%%dualG6#FcxFcoF_x@'2FbxF:F:/Fbx
F:F`o-Fg[l6%-Fhgl6$,$-F\hl6#FfxFcoFbxF\\lFbx/F9F`al@%2FfxFbx7"C$>Fgr-Fhgl6$,$-F
\hl6#&Fcx6#F`alFcoFfx7#-Fcq6$-Fg[l6%FgrF\\lFin/Fin;FbxFfx-FG6#%Bwrong~number~or
~type~of~argumentsGF$F$F$%&bettiGf*6$F*%"nG6#F3F$F$C%@$F8-F<6#%>usage:~betti(X)
~or~betti(X,n)G@$4-FM6#&FD6#%'betti_GC$@$4-FM6#F^t-F<6#%Dneed~to~compute~additi
vebasis~firstG>F][m7#-Fcq6$-Fgp6#&F^t6#Fgr/Fgr;F:Fjn@%F_x&F][m6#,&F]glF`oF`oF`o
F][mF$F$F$%)morphismGf*6&Fh\lF*%"YG%#sbG6#F2F$F$C)@$F8-F<6#%Musage:~morphism(f,
X,Y)~or~morphism(f,X,Y,sb)G>FDF]`l>&FD6#%(source_GF]gl>Fa]l9&>Fjn,&&F]glF[oF`o&
Fg]mF[oFco@%/F9""%@'3-FB6$9'Fdv-FB6$&Fc^mFdxFf`l>&FD6#%/upperstardata_G-F]al6#F
c^m3Fa^m/-FgpF\_m-Fgp6#&Fg]mFdbl>Fh^m-Fcq6$/&Fb_mF_\m&Fc^mF_\m/Fgr;F`oF__m-FG6#
%8invalid~fourth~argumentG>Fh^m%%NULLGFDF$F$F$%-normalbundleGf*Fg\lF$F$F$C%@$F8
-F<6#%7usage:~normalbundle(f)G@$4-FM6#Fadl>Fadl,&&Fc]mFbdlF`o-%*upperstarG6$FD&
Fa]lFbdlFco,$FadlFcoF$F$F$Fe]lf*F)F$F$F$C'@$F8-F<6#%5usage:~setvariety(X)G>F\^l
Fjn>F[yFD-F^p6%F`pFa^l-Fcp6&%4currentvariety_~is~GF[y%*,~DIM~is~GF\^lF`^lF$6$F
\^lF[yF$%)porteousGf*6%F1%"BGF.6'Fbjl%"mG%#ccGF2F3F$F$C'@$F8-F<6#%7usage:~porte
ous(A,B,k)G>Fgr-%%rankGFT>Fin-F`cm6#F]gl@$2FinFgr-F<6#-Fbbm6%-F\hlFccm-F\hlFTFg
]m@'1FgrFg]mF`o2Fg]mF:F:C$>F^o-%&chernG6%F:,*FinF`oFgrF`oFg]m!"#FcoF`o,&F]glF`o
FDFco-%'expandG6#-&Fjr6#%$detG6#-F_q6#7#-Fcq6$7#-Fcq6$&F^o6#,,FinF`oFg]mFcoFjoF
`oFfoFcoF`oF`o/Fjo;F`o,&FgrF`oFg]mFco/FfoF[fmF$F$F$%.tangentbundleGf*F)6'%$curG
Fh^l%"rGFealF1F$F$C&@$F8-F<6#%8usage:~tangentbundle(X)G@$4-FB6$FD.FE-FG6#%Gargu
ment~must~be~a~variety~or~morphismG@$Fh`mC%@+/&FDFdy%1projectivespace_GC&>FgrF[
y>FfoF\^lF_fl>Fadl,&*&,&F\^lF`oF`oF`oF`o-%"oG6$-F]al6#FcblFDF`oF`oFcoF`o/Fdgm%.
grassmannian_GC(>FgrF[y>FfoF\^lF_fl>F^o&FD6#%'arank_G>Fin&FD6#%&name_G>Fadl-%$H
omG6$,&F^oF`o-Fcp6$.%"QGFinFcoFdim/FdgmFfyC(>FgrF[y>FfoF\^l-%#upGFT>Fjo&FD6#%.v
ectorbundle_G>FinF`hm>Fadl,&-%#&@G6$-F\hlF[q-F^hmF^[lF`oFcoF`o/FdgmFhyC(>FgrF[y
>FfoF\^lF\jm>FjoF_jm>FinF\im>Fadl-Faim6$,&FjoF`oFdimFcoFdim-FG6#%Qnot~enough~in
formation~to~compute~tangent~bundleG>&FDFjz-%%toddGFj`m@$-FMF_\mC$>F[yFgr>F\^lF
foFadlF$6$F[yF\^lF$Fbdmf*F$F`glF$F$C$@$F8-F<6#%Nusage:~chern(A)~or~chern(p,A)~o
r~chern(p,q,A)G@)Fhx-FhglF]hlF_x@'F_hlF:F`hlF`o-Fg[l6%-Fhgl6$FfxFbxF\\lFbxFhhl@
%FjhlF[ilC$>Fgr-Fhgl6$FcilFfxFeilF\jlF$F$F$%&wprojGf*6''F*Fh_l'%"hGFh_l'%"wG-Fd
v6#FjalFf^lFg^l6)F1%"xGFbjl%&edgesGFi^lF2F3F$F$C'@$F8-F<6#%Lusage:~wproj(X,h,w)
~or~wproj(X,h,w,options)G>F^o-Fgp6#Fg]m>Fgr-&Fjr6#F]s6#-&Fjr6#%(delrowsG6$-%9sc
hubert/maptounitvectorGFg^n;F^oF^o?(F^rF`oF`oF^oF\wC$>Fjo-%%igcdG6#-Fcq6$&Fgr6$
F^rF]q/F]q;F`o,&F^oF`oFcoF`o>Fgr-&Fjr6#%'mulrowG6%FgrF^r*$FjoFco-%-toricvariety
G6(FDF]gl-%%evalGF_\m/%$sriG7#-%(productG6$.-Fcp6$.F]glF]q/.F]q;F`oF^o/%&conesG
7#-Fcq6$-%'subsopG6$/F]qF_`m7#-%"$G6#Fjan/F]qFjan&Fcx6#;F^^mF9F$F$F$%&sheafGf*F
$6$F2FealF$F$C&@$F8-F<6#%Zusage:~sheaf(rank,classes)~or~sheaf(rank,classes,vari
ety)G@%Fhhl>Fin&FcilF[o>FinF\^l@$4-FB6$FfxFdv-FG6#%Rsecond~argument~must~be~a~l
ist~(of~Chern~classes)G,&FbxF`o-%.schubert/loggG6$,&F`oF`o-%$sumG6$*&&FfxF_\mF`
o)F\\lFgrF`o/Fgr;F`o-FgpFghlF`oFinF`oF$F$F$%&grassGf*6&F.FbfmFh^l%&strngG6%F2%%
relgG%#stGF$F$C6@$F8-F<6#%Kusage:~grass(k,r,c)~or~grass(k,r,c,string)G>-Fcp6$.%
"GGFg]mF]`l>&FjenF[o*&FDF`oFfdmF`o>&FjenFdbl7#-Fcp6$.Fg]m;F`oFD>&FjenF\cl7#-Ffb
n6#Fgfn>F\^lF]gl>-Fcp6$FffnF:F`o>Fin-%#&/G6$F`o-Fc[l6$*&-Fcp6$FffnFgrF`oFidnF`o
/Fgr;F:FD>&FjenFdcl7#-Fcq6$-Fg[l6%FinF\\lFgr/Fgr;,(F]glF`oFDFcoF`oF`oF]gl>F\^lF
`fn>-Fcp6$FfimFg]m-%'bundleG6$FDFg]m>&FjenF[dl)-Fcp6$FffnFDFfdm>&FjenFdyFchm>&F
jenFihmF]gl>&Fjen6#%'qrank_GFD>&FjenF]imFg]m-Fgn6#Fjen@$F]^mC%>F^o-Fj`l6$Fc^mF_
al@$5/F^oF\fl/F^oF^dl-F^fmF]jn@$5Fejn/F^oFiel-F'F]jn-Fe]lF]jnF`^lF$Fb^lF$%&stri
pGf*F$F$6$/%(builtinGFhdm%)rememberGF$F$F$F$F$%$&-*Gf*6$Fh\lF^^n6*F*Fi\mFgbmFbj
lF3F.%$monG%$cofGF$F$C,@$F8-F<6#%Ausage:~lowerstar(f,y)~or~f~&-*~yG@$5FjjmFhimC
%>Far7#-%'coeffsG6%-FhdmFccmFcbl.F^r>F^r7#F^r-F<6#-Fhdm6#-Fc[l6$*&&FarF[qF`o-Fi
q6$&FD6#%+lowerstar_G&F^rF[qF`o/Fjo;F`o-FgpF`r>FgrFc]m>FinFa]l@$4-FM6#&FinF_t-F
'F^[l>F^o&FinF[o>Ffo&FgrF[o>F]q-%,codimensionG6$FgrF]gl@$2F^o,&FfoF`oF]qFco-F<6
#F:-Fc[l6$*&-F`[l6$Fgr*&-F_am6$FD&&&FinF^u6#F]_oF[qF`oF]glF`oF`o&&Fa^o6#,(F^oF`
oFfoFcoF]qF`oF[qF`o/Fjo;F`o-Fgp6#&Fa^oF[`oF$F$F$%+insertedgeGf*6(Fi\mF*F^^n%"vG
Ff^lFg^l6.FbjlFi^lF2F3%#ycG%$yedG%%bigcG%&scsetG%%coneG%(compsetGFhbm%#scGF$F$C
2@$F8-F<6#%Zusage:~insertedge(Y,X,x,v)~or~insertedge(Y,X,x,v,options)G>Fgr-Fgp6
#&F]gl6#%/edgevariables_G>FinFj]m>F]q-&Fjr6#%'matrixG6$,&FgrF`oF`oF`oFin?(F^oF`
oF`oFgrF\w?(FfoF`oF`oFinF\w>&F]q6$F^oFfo&&F]gl6#%'edges_GFhbo?(FfoF`oF`oFinF\w>
&F]q6$FcboFfo&Fc^mFhp>Fjo-Fau6$&F]gl6#%'cones_G%$setG>F^r<">8/-%*whichconeG6$F]
glFc^m>Far-Fau6$F\doFhco?&FisFjoF\w@$/-%*intersectG6$-Fau6$FisFhcoFarFar>F^r-%&
unionG6$F^r<#Fis>Fjo-%&minusG6$FjoF^r>F[tFjco?&8.F^rF\w>F[t-F]eo6$F[t<#-Fbeo6$-
Fau6$FfeoFhcoFar?&F^oF\doF\w?&FfoF[tF\w>Fjo-F]eo6$Fjo<#7%-F]alFhp-F]al6#-Fbeo6$
Far<#F^oFcbo-Fj`n6'FD7$-F]alFhaoFg]mF]q-Fau6$FjoFdv&Fcx6#;""&F9F$F$F$Fj[nf*6#F1
6%Fi^lF2%$tmpGF$F$C%@$F8-F<6#%/usage:~todd(A)G>F^o-Fadn6$-%/schubert/stripG6#-F
au6$-%'taylorG6%*(F\\lF`oFgrF`o,&F`oF`o-%$expG6#,$*&F\\lF`oFgrF`oFcoFcoFcoF\\l,
&F\^lF`oFjvF`o%(polynomGF\^l-Fhgl6$-Fedn6$*(-Fg[l6%F^oFgrFinF`o-%*factorialGF^[
lF`o-Fg[l6%FDF\\lFinF`o/Fin;F:F\^lF\^lF$F$F$%-grobnerbasisGf*6$F*%&orderG6$%$or
dG%&grelsGF$F$C)@$F8-F<6#%Pusage:~grobnerbasis(X)~or~grobnerbasis(X,order)G@$4F
jdl-FG6#%/need~relationsG@%Fhx>Fgr.%%tdegG>FgrF]gl>&FD6#%'order_GFgr>Fin-&%(gro
bnerG6#.%'gbasisG6%FcclFcblFgr>&FD6#%,grelations_GFin-Fcp6%%=grobner~basis~comp
uted~with~G-FgpF^[l%*~elementsGF$F$F$%*dimensionGf*F)F$F$F$C$@$F8-F<6#%4usage:~
dimension(X)G@%F@-FG6#%;argument~must~be~a~varietyGFjnF$F$F$F\hlf*FggoF$F$F$C$@
$F8-F<6#%/usage:~dual(A)G-Fifl6$/F\\l,$F\\lFco-F]anFTF$F$F$F_amf*6$Fh\l%"yG6$F2
%"pGF$F$C%@$F8-F<6#%Ausage:~upperstar(f,y)~or~f~&^*~yG>Fin-Fifl6$Fh^mF]gl@'-%$h
asG6$Fin.F\\l-Fhdm6#-Fedn6$*&FahnF`oFidnF`o/Fgr;F:&Fc]mF[o2Fj_p-Fi^o6$Fc]mFinF:
FinF$F$F$%'tensorGf*6$F1Febm6'Ff^lFg^lFh^lF2F.F$F$C(@$F8-F<6#%=usage:~tensor(A,
B)~or~A~&@~BG>Fgr-F_q6#F_jo>FinFh`p>F^oF:?(FjoF:F`oF\^lF\wC%>&FgrF[q-Fg[l6%FDF
\\lFjo>&FinF[q-Fg[l6%F]glF\\lFjo>F^o,&F^oF`o*&-Fcho6#-Fedn6$*&&FgrFhpF`o&Fin6#,
&FjoF`oFfoFcoF`o/Ffo;F:FjoF`o)F\\lFjoF`oF`o-FchoFhoF$F$F$Fcgnf*F``pFa`pF$F$C+@$
F8-F<6#%?usage:~division(A,B)~or~A~&/~BG>FgrFh`p>FinFh`p>F^oFh`p?(FjoF:F`oF\^lF
\wC$>F_apF`ap>FcapFdap@$/&FinF__oF:-FG6#%@no~constant~term~in~denominatorG>&F^o
F__o*&&FgrF__oF`oFecpFco?(FjoF`oF`oF\^lF\w>&F^oF[q-Fcho6#*&,&F_apF`o-Fedn6$*&&F
^oFhpF`oF_bpF`o/Ffo;F:,&FjoF`oFcoF`oFcoF`oFecpFco-Fedn6$*&FgdpF`o)F\\lFfoF`o/Ff
oF_joF$F$F$FfjmF_`p%$&-!Gf*6$Fh\lF16$FigoF2F$F$C%@$F8-F<6#%Cusage:~lowershriek(
f,A)~or~f~&-!~AG@$4-FB6$7#Fcx7$FE%)anythingG-FG6#%0wrong~argumentsG@%5FhimFjjmC
$F\jm-Fhdm6#*&-%*lowerstarG6$FD-Ffjm6$F]glFh[nF`o)F\\lFjnFcoC'-Fe]l6#Fc]m@$Fh`m
>FadlF\am@$4-FM6#Fh[n-F][lFT>Fgr-Fhdm6#F\gp-Fhdm6#-Fc[l6$*&-Fjfp6$FDFhilF`o)F\\
l,&FinF`oFjnFcoF`o/Fin;-%$maxG6$F:FjnFj_pF$F$F$%'blowupGf*F[]m6)F*Fi\mF-Fi^lF.%
"sG%"NGF$F$C4@$F8-F<6#%1usage:~blowup(i)G>-Fcp6$.FebmFDF]`l>FgrFa]l>FinFc]m>F^o
Ff^o>FfoFd^o>&FeipF[oF^o>&FeipFdbl7$-Fcp6$.%"EGFD-F]al6#&FgrFdbl>&FeipF\cl7$F`o
-F]al6#&FgrF\cl@$-FM6#&FgrF[dl>&FeipF[dlFa[q-FS6#Feip-Fe]lF^[l>F^r-F``mFT>&Feip
FZ-%%copyG6#&Fa]lFZ?(FjoF`oF`oF^oF\w?(F]qF`oF`o-Fgp6#&&FgrFP6#,&F^oF`oFjoFcoF\w
>&Fj[q6#*&)FajpFjoF`o&Fc\q6#F]qF`o*&-F`[l6$Fin*&-F^gl6$,(FjoF`oF^oFcoFfoF`oF^rF
`o-F_am6$FDF\]qF`oF`o)Fco,(F^oF`oFfoFcoF`oF`oF`o-Ff\m6%-Fcp6$.Fe^pFDFeipFgr-Fe]
lFe[qF`^lF$F$F$%(composeGf*6%Fh]nF[_lFh\l6(%$tarG%%varyG%%numbG%$subG%&substGF2
F$F$C-@$F8-F<6#%6usage:~compose(h,g,f)G@$4/&F]glFd]m&Fg]mFb]l-FG6#%NComposition
~of~these~morphisms~is~not~definedG>Fc]m&Fg]mFd]m>Fgr&F]glFb]l>Fa]lFgr>FinFgjp>
F^oFi\p?(F]qF`oF`oF^oF\w>&FfoF]]q-Fifl6$&Fg]mFi^m&7#&F]glFi^mF]]q>Fjo-Ffbn6$.F^
`qFhan>Fh^mFjoFDF$F$F$%&schurGf*F$6$F2F3F$F$C$@$F8-F<6#%enusage:~schur(partitio
n,A)~or~schur(partition,partition2,A)G-Fhdm6#-Fifl6$-Fcq6$/-Fcp6$.Fh]nFgr-F^gl6
$FgrF`el/Fgr;F`o-Fau6$Fbx%"+G-%*SF/jt_detG6%-Fcq6$&FcxF^[l/Fin;F`o,&F9F`oFcoF`o
F:F[bqF$F$F$%&twistGf*6%FbfmFh\lFc^p6%%#ffGF2Fe^pF$F$C%@$F8-F<6#%4usage:~twist(
r,A,y)G>FgrFf\o-%(collectG6$-Fhdm6#,&F`oF`o-Fedn6$*&)F\\lF^oF`o-Fedn6$*(-%)bino
mialG6$,&FDF`oFinFco,&F^oF`oFinFcoF`oFhilF`o)Fg]mFhdqF`o/Fin;F:F^oF`o/F^oFgfnF`
oF\\lF$F$F$%.multiplepointGf*6$Fh\lF.62Ff^lFh^l%#coGF2F3%"lGFgbmFbjl%$outGFe^p%
%pushG%"qGFbfm%#sqG%#ssG%"uG6#Fb[oF$C-@$F8-F<6#%:usage:~multiplepoint(f,k)G@$/F
]glF`o-F<Fdx>FecpF`o>Far,$FjnFco>&F[tF__o&FinF`r?(FfoF`oF`o*&FarF`o,&F]glF`oFco
F`oF`oF\wC$>&82FhpF:?(FjoF:F`oFfoF\w?(F]qF:F`o,&FfoF`oFjoFcoF\wC$@%1FjoFar>F^o-
&%)combinatG6#%)numbcombG6$,&FarF`oFjoFcoF]q>F^o*&)FcoF]qF`o-Fggq6$,*FjoF`oFarF
coF]qF`oFcoF`oF]qF`o>F]gq,&F]gqF`o*(F^oF`oFcapF`o)83FagqF`oF`o?(FjoF`oF`o*&,&Ff
oF`oF`oF`oF`oFarF`oF\w>&F\do6$F`oFjo&Fin6#,&FarF`oFjoF`o?(FfoF:F`o,&F]glF`o!"$F
`oF\wC(>Ffeo-Fhdm6#-Fifl6$-Fcq6$/&FinF]r&F^gqF]r/F^r;F`oFihq&F[tFhp?(FjoF:F`oFi
hqF\w>&Fgr6$FfoFjo-Fg[l6%FfeoFghqFjo@$2F:Ffo?(F]qF:F`o*(,(F]glF`oFfoFcoFedmF`oF
`oFjhqF`oFarF`oF\wC$>&F\do6$FjhqF]qF:?(F^rF:F`o,&FfoF`oFcoF`oF\w?(FjoF:F`o*&,&F
^rF`oF`oF`oF`oFarF`oF\w>F_[r,&F_[rF`o*&&Fgr6$F^rFjoF`o&F\do6$,&FfoF`oF^rFco,&F]
qF`oFjoF`oF`oF`o>&F[t6#FjhqF:?(F]qF:F`oFfoF\w?(FjoF`oF`o*&,&F]qF`oF`oF`oF`oFarF
`oF\w>F`\r,&F`\rF`o*&&Fgr6$F]qFjoF`o&F\do6$,(FfoF`oF`oF`oF]qFcoFjoF`oF`o>F`\r*&
-Fhdm6#F`\rF`o,&FfoF`oFjvF`oFco>Fis-F_am6$FD-Fjfp6$FD-F]eq6$FDFjfq?(FfoF:F`o,&F
]glF`oFedmF`oF\wC%>81F_`m?(80F`oF`oFihqF\w>F^^r6$F^^r/&Fin6#F`^r-Fbdm6$F`^rFh[q
>Fis,&FisF`o**)FcoFjhqF`o-Fban6$.,(F]glF`oFcoF`oFjoFco/.Fjo;F:FfoF`o-Fifl6$F^^r
FajqF`o-F]eq6$FD,(F]glF`oFcoF`oFfoFcoF`oF`o-FhdmFjtF$F$F$F^dof*6$F*Fh`o6.Fi^lFb
jlF2%*smallconeGF^ao%(conesetG%%submGF5%#vvG%%varsG%#eqG%$lhsGF$F$C)@$F8-F<6#%6
usage:~whichcone(X,v)G>Fin-Fgp6#&FDFjao>FgrFjn>Far7#-Fcq6$F^o/F^o;F`oFgr>Ffo<#-
Fcq6$F^o/F^o;F`oFin?&Fjo&FDFfcoF\wC$>F]q-Fau6$FjoFhco@$4/-Fgdo6$F]qFfoFjcoC&>F^
r-&Fjr6#%*submatrixG6%&FDF[coFjoFar>F[t-F_bo6%F`oFgr7#-Fcq6$-Fcp6$FhsF^oFaar>F
\do-%&evalmG6#-Fdu6$F[tF^r@$-&%(simplexG6#%)feasibleG6$<#-Fcq6$/&F\do6$F`oF^o&F
]glFhoFaar%,NONNEGATIVEG>Ffo-Fgdo6$FfoF]q-Fau6$FfoFdvF$F$F$Fa^lf*F$F$F$F$F]bmF$
F$F$F]jmf*Fg\lF$F$F$C%@$F8-F<6#%-usage:~up(f)G@'-FMFagpF`gpFf]l>F\^l,&FjnF`oFh]
lF`oF]^lF`^lF$Fb^lF$F][lf*F)F$F$F$C(@$F8-F<6#%5~usage:~toddclass(X)G@$F@-FG6#%:
usage:~toddclass(variety)G@$Fh`m-FG6#%Jneed~tangent~bundle~to~compute~Todd~clas
sG@%FferF`gpF_fl>Fh[nFi[n-Fcp6$%8toddclass~computed~for~GFDF$F$F$%)divisionGFfb
p%-blowuppointsGf*6%F*F.Fj^l6'F2F3FbfmFh`o%%relsGF$F$C/@$F8-F<6#%;usage:~blowup
points(X,k,e)G>-Fcp6$FgipFg]mF]`l>&FhgrF[oFjn>&FhgrFdbl7$F`hm-Fcp6$Fffn;F`oF]gl
>&FhgrF\cl7$-F]al6#F[cl-Fcq6$F`o/FgrFahr@$-FM6#Fjcl>&FhgrF[dlFjcl>&FhgrFZ-F\\qF
X-Fe]l6#Fhgr?(FgrF`oF`oF]glF\w>&F`ir6#)FhgnF\^l)FcoF\hm@$3FjdlF[irC%>Fjo7$-F]al
F[el-Fcq6$,&FhirF`o*&)FcoF\^lF`oF^irF`oF`oFihr?&FfoFcblF\w?(FinF`oF`oF]glF\w>Fj
o7$-F]alF[q*&FfoF`o-Fcp6$FffnFinF`o?(FgrF`oF`oFjfqF\w?(FinFcboF`oF]glF\w>Fjo7$F
ijr*&FhgnF`oF[[sF`o@$Fi`mC%>&FhgrFdclFjo>F^o-F^hm6#-Fc[l6$FhgnFihr>&FhgrFbdl,*F
adlF`o*&FjnF`o,&F`oF`o-F\hlFhoFcoF`oFcoF^oF`oFcoF`o-Ff\m6%-Fcp6$F]^qFg]mFhgrFDF
`^lF$F$F$F_zFaep%+normalformGf*F$6$F*F^^nF$F$C%@$F8-F<6#%Husage:~normalform(c)~
or~normalform(X,c)G@&F[fpC$>FgrFbx>FinFfxFhxC$>FgrF[y>FinFbx@%-FM6#&FgrFd\p-&F]
\p6#.%(normalfG6&FinFg]sFgjp&FgrFh[pFinF$F$F$%%ProjGf*6&Fh\lF1Fh^lF^_l6'FafmFbf
mF2%$segGFcenF$F$C4@$F8-F<6#%Iusage:~Proj(f,A,c)~or~Proj(f,A,c,option)G>FgrF[y>
FinFbcm>FDF]`l>F_jmF]gl>Fjn,&FinF`oFcoF`o>Fh]lF\^l>Fcbl7#Fg]m>F[cl7#F`o>Ffo-F^g
l6%F:F\^lF]gl?(F^oF^_sF`o,(F\^lF`oFinF`oFcoF`oF\w>&Fd]o6#)Fg]mF^o&Ffo6#,(F^oF`o
FinFcoFjvF`o>F[yFgr>F\^lFher>FdgmFfy@$F]^mC$>Fjo-Fj`l6$&Fcx6#F^^mF_al@$5/FjoF\f
l/FjoF^dl-F^fmFT>&FD6#%)section_G)Fg]mF^_sF[bmFDF$F`\nF$%&wedgeGf*6$Fe^pF16$Fbf
mFgbmFieqF$C%@$F8-F<6#%2usage:~wedge(p,A)G>FgrFbcm@+52FDF:2FgrFDF:/FDF:F`o/FDF`
oF]gl2Fgr,$FDFjv-Ffjm6$-%,determinantGFccm-F\hl6#-Fdas6$,&FgrF`oFDFcoF]gl-Fcho6
#*&-Fc[l6$*&-Fdas6$FinF]glF`o)Fco-Ffjm6$,(FDF`oFinFcoF`oF`o-Fifl6$/F\\l*&F\\lF`
oFgdqF`oF]glF`o/Fin;F:,&FDF`oFcoF`oF`oFDFcoF$F$F$%*porteous2Gf*FdbmF$F$F$C$@$F8
-F<6#%8usage:~porteous2(A,B,k)G-Fj`q6$7#-Ffbn6$,&F_cmF`oFg]mFco,&FbcmF`oFg]mFco
FfdmF$F$F$%-schurfunctorGf*F$6(F1F3FbfmF]ipF.%%tempGF$F$C(@$F8-F<6#%cousage:~sc
hurfunctor(partition,A)~or~schurfunctor(partition,partition2,A)G>FgrF`el>F^o-F`
cmF_\m>FfoFcbq>F]q-Fhdm6#-Fifl6$-Fcq6$/-Fcp6$F[bqFjo-%%SymmG6$FjoFgr/FjoFjanFfo
-Fhdm6#-Fc[l6$*&-Fg[l6%F]qF\\lFjoF`oFdbpF`o/FjoF_joF$F$F$%&GrassGf*6'Fh\lF.F1Fh
^lF^_l6/%$lowG%$ltmGFgeq%#tmGFj\mFbfmFbjlF2F3Fi^l%#PPG%#MMGFcenF$F$C=@$F8-F<6#%
Ousage:~Grass(f,k,A,c)~or~Grass(f,k,A,c,option)G>FDF]`l>F]q-F`cmFg^n@$52F]glF:2
F]qF]gl-FG6#%6Grassmannian~is~emptyG>FhhmF]q>&FDFhinF]gl>F_jmFg]m>Fjn*&F]glF`o,
&F]qF`oF]glFcoF`o>Fh]lF\^l>F\imFc^m>Fcbl7#-Fcp6$.Fc^mFahr>F[cl7#-Ffbn6#Fahr>F`a
s)-Fcp6$FhisF]glFais>FdgmFhy>Fh^mF_`m>F^o-F^gl6%F`oF\^lFg]m>Fjo6$-Fcq6$/-Fcp6$F
[bqFar&F^oF`r/Far;F`oF\^l-Fcq6$/F[[tF:/Far;F\hm,&F\^lF`oF`isF`o>Far.FarFR?(F^rF
:F`oF\^lF\wC)-F^p6%F`pFap-Fcp6$%6starting~codimension~G,&F\^lF`oF^rFco>Ffo-%3sc
hubert/tosmatrixG6$,&F^rF`oF`isF`oF]gl>Ffeo-%'SF/ParGFc\t>Fgr-&Fjr6#.%'vectorG6
#-Fgp6#Ffeo?(FisF`oF`oF_]tF\w>&FgrFjt-Fifl6$Fjo-F[em6#-%-SF/jt_matrixG6%&FfeoFj
t7#-Ffbn6$FaisF]glF[bq>Fin-&Fjr6#.Ffu6$FfoFgr?(FisF`oF`oF_]tF\wC%>F[t-Fgp6#F[^t
>&F\doFjt*&-Fban6$.)-Fcp6$FhisFar,&&F[^tF`rF`o&F[^t6#,&FarF`oF`oF`oFco/Far;F`o,
&F[tF`oFcoF`oF`o)-Fcp6$FhisF[t&F[^tFcvF`o>&Fd]o6#F[_t&FinFjt-F^p6%F`pFap%;lower
star~computation~doneG>F\^lFher>-Fcp6$FfimFc^m-F[inF_do>&FD6#%0quotientbundle_G
Fh`t@$/F9FegoC$>F`^r-Fj`l6$&Fcx6#FegoF_al@$5/F`^rF^dl/F`^rF\flC$-F^p6%F`pFap%5s
tart~tangent~bundleGF^asF[bmFDF$Fb^lF$Fhfsf*6$FgbmF16(%&todchG%$todGFbfm%#sAGF2
Ff^lF$F$C%@$F8-F<6#%1usage:~Symm(p,A)G@$4-FM6#&%&SYMM_GFccmC)>F^oFbcm>FfoFe_s>F
\^l,(F\^lF`oF^oF`oFcoF`o>Fin-Fj[n6#,&-Ffjm6$Fjcm-F^hmF]]qF`oFcoF`o>Fgr-Ffjm6$Fi
n-F^hm6#*&.FbjlF`oF]qF`o>F\^l,(F\^lF`oF^oFcoF`oF`o>F^ct-Fhdm6#*&-Fedn6$*&&Ffo6#
,&FjoF`oF`oF`oF`o-Fg[l6%FgrF]q,(F^oF`oFcoF`oFjoF`oF`oFbgsF`o)F\\lFa`nFco-Fifl6$
/FbdtFDF^ctF$6$F\^lF_ctF$Fibsf*FggoF$F$F$C$@$F8-F<6#%6usage:~determinant(A)G-F^
hm6#-Fg[l6%FDF\\lF`oF$F$F$%%projGf*6%FbjlFh]nF]_l6#FcenF$F$C/@$F8-F<6#%Eusage:~
proj(n,h)~or~proj(n,h,option)G>-Fcp6$.%"PGF]glF]`l>&F[gtF[oFD>&F[gtFdbl7#F]gl>&
F[gtF\clFc_s>&F[gtFdcl7#)F]gl,&FDF`oF`oF`o>&F[gtF[dl)F]glFD-Fgn6#F[gt>F\^lFD>&F
[gtFdyFegm@$FhhlC%>Fgr-Fj`l6$Fg]mF_al@$5/FgrF\fl/FgrF^dl-F^fmF_ht@$5Fjht/FgrFie
l-F'F_ht-Fe]lF_htF`^lF$Fb^lF$%.bundlesectionGf*6$%"ZGFhw6&F*%'classZGF.FgbmF$F$
C1@$F8-F<6#%:usage:~bundlesection(Z,F)G@$Fe_l-FG6#%Iusage:~bundlesection(name,v
ector~bundle)G>FgrF[y>Fin-Fbdm6$FbcmF]gl>FD-FE6#7%/F\o,&F\^lF`oFbcmFco/FeblFgjp
/F]clF][q-Ff\m6%-Fcp6$.F2FDFDFgr>&F_[uFdy%/bundlesection_G>Fadl-F_am6$F_[u,&&Fg
rFbdlF`oF]glFco>FdgmFd[u>&FD6#%.structuremap_GF_[u>&FD6#%'class_GFinFR?(F^oF:F`
oFjnF\w?&FfoFgoF\w>&FYFhp-F`[l6$Fgr*&FfoF`oFinF`oF_flF`^lF$F$F$F`cmf*FggoF$F$F$
C$@$F8-F<6#%/usage:~rank(A)G-Fhdm6#-Fifl6$/F\\lF:FDF$F$F$%.verifydualityGf*F)6$
F2%$matGF$F$C%@$F8-F<6#%8usage:~verifyduality(X)GF_fl?(FgrF:F`oFjnF\wC$>Fin-%$m
apG6$F`[l-Fa^t6$F^\m-Fir6#&F]u6#,&FjnF`oFgrFco-%&printG6#-Fcp6$%%det~G/-F]anF^[
l-&Fjr6#.F]emF^[lF$F$F$%%symmGf*Ffas6$FbfmF.FieqF$C$@$F8-F<6#%1usage:~symm(p,A)
G@'F`bsF:FbbsF`oC$>Fgr-%$minG6$FDFbcm-Fcho6#-Fc[l6$*&-Ffjm6$Fecs-Fg_u6$FgdqF]gl
F`o)Fco,&F`oF`oFinF`oF`o/FinFbarF$F$F$%+totalspaceGf*6%Fh\lF*F^_l6.F2Feal%$DimG
Fi^l%#bbG%$dbbGFh]uFcenFh^lFbfmF3F.F$F$C&@$F8-F<6#%Qusage:~totalspace(f,X)~or~t
otalspace(f,X,option)G>-Fcp6$.%"TGFDF]`l@$F_\oC/>FinFj]m>F^oFjn>&F^buF[o,&FinF`
oF^oF`o>&F^buF\zF]gl>&F^buFdbl7$F`hm-F]al6#&F]glFdbl>&F^buF\cl7$Fehr-F]al6#&F]g
lF\cl>&F^buFdyFdgm>&F^buFbzFD>&F^buF[dl*&&F]glF[dlF`oF`asF`o>Fc]mF^bu>Fa]lF]gl-
Fe]l6#F^bu@$FhhlC%>FarFfht@$5/FarF\fl/FarF^dlC$>&F^buFbdl,&FadlF`o&F]glFbdlF`o>
&F^buFjz-Fj[n6#F\eu@$5Fhdu/FarFielC(-F^p6%F`pFap%<start~generating~dual~basesG@
&FhimC$>FisF`hm>&FD6#%'fiber_G-FE6#7'/F\oF^o/Febl7#Fis/F]clFc_s/Fecl7#)FisFfv/F
\dl)FisF^oFjjmC(>FisF\im>F[tFhhm>F\doF]is-F]en6%F\doF[tFis>-Fcp6%FfimFisFD-Fcp6
$FfimFis>F^fu-Fcp6$F\fnFis-F'6#F^fuFadu@$Fjjm>Ffgu-F[in6$F\doFis?(FfoF:F`oFhbuF
\wC)>FjoF_`m>F]qF_`m?(Fgr-Fhhp6$F:,&FfoF`oF^oFcoF`o-Fc`u6$FfoFinF\wC$>Fjo6$Fjo-
Fcq6$-Fcq6$-Fhdm6#*&&&&F]glF_tF_\m6#F\doF`o&&&F^fuF_t6#,&FfoF`oFgrFcoF`]tF`o/Ff
eo;F`o-Fgp6#Fjiu/F\do;F`o-Fgp6#Ffiu>F]q6$F]q-Fcq6$-Fcq6$-Fhdm6#*&&&&F]glF^u6#,&
FinF`oFgrFcoFhiuF`o&&&F^fuF^u6#,(F^oF`oFfoFcoFgrF`oF`]tF`oF^juFbju>&&F^buF_tFhp
7#Fjo>F^r-Fb^u6$F`[l-Fa^t6$-F_q6#F\\v-Fir6#-F_q6#7#F]q>F^r-Fir6#-F`sF]r>&&F^buF
^u6#,(FinF`oF^oF`oFfoFco-Fau6$-Fa^t6$F^rFf\vFdvF`^lF$F$F$Fj`nf*6%Ff]nF^^nF_^n6H
Fi^lF\bnFagrFbjlF_`r%#edG%#lrGF2Fe^p%%detsGF3%#mcG%#spGF``r%#vxG%%specG%"SG%#SR
GFh^l%%candGFhbm%#ddG%(inidealG%$inmG%#lfGFh]u%&pconeGFeeq%$timG%&ampleG%&infan
GFgbmFbfm%&optioG%$opsG%$solGF^_l%%sridGF$F$CS>8@-%%timeGF$@$F8-F<6#%Gusage:~to
ricvariety(X,x,edges,options)G-F^p6%Fego.%&toricG/%<enter~toricvariety~at~time~
G,&Fb_vF`oFa_vFco@'-FB6$Fg]m-Fdv6#F[^n>F]q-F_boFg^n-FB6$Fg]mFabo>F]q-F]anFg^n-F
G6#%Sthird~argument~must~be~a~matrix~or~a~list~of~listsG>Fgr-&Fjr6#%'coldimGF]]
q>Ffo-&Fjr6#%'rowdimGF]]q@'-FB6$F]glFdv>F^gqF]gl-FB6$F]glFh_l>F^gq7#-Fcp6$Fgan;
F`oFfo-FG6#%Nsecond~argument~must~be~name~or~list~of~namesG-F^p6%F`pFj_v/%3edge
variables~are~GF^gq>8FFjco?&8E7#FibnF\w@/-FB6$F\cv%)equationGC$>8H-Fj`l6$-Fb`r6
#F\cvF_al@*5/Fdcv.%$PicG/Fdcv.%$picG>Fghq-%$rhsGFhcv/Fdcv.%$ampG>8AFbdv/Fdcv.%$
conG>FinFbdv/Fdcv.F_an>8IFbdv-FB6$F\cvF[^n>FhdvF\cv-FB6$F\cvFb`v>FinF\cv-FB6$F
\cv-Fdv6#Fbio>F`evF\cv-FB6$F\cv-Fdv6#Facv>FghqF\cv-FB6$F\cv%'symbolG>Fjbv-F]eo6
$Fjbv<#-Fj`l6$F\cvF_al-FG6#/%?argument~not~of~correct~type:~GF\cv>Fjo-F_bo6%F`o
FfoF^gq>F^r-Fdu6$FjoF]q@$4-FM6#Fghq>FghqF[il>8G-%&solveG6$<$-F]alFggv-Fcq6$&F^r
6$F`oFar/FarFbar<#-F]al6#F^gq@$/FjgvF_`m-FG6#%Egiven~elements~of~Pic~are~depend
ent!G>F`^r6$-Fcq6$-Fb`r6#&FghqF`r/Far;F`o-FgpFggv-F]al6#-Fb^u6$Fb`r-%'selectG6$
f*6#Fa`rF$6$%)operatorG%&arrowGF$/-Fb`rFT-FcdvFTF$F$F$Fjgv>F^^r-Fifl6$-F]al6#Fj
gvF^gq-F^p6&F`pFj_v/%+Pic~basis~G7#F`^r/%)at~time~GF^`v@$-FMF^[lC$>F[t-Fcq6$-F[
em6#-Fgbr6%F]q7#-F]al6#&Fis6#FbarFbar/FisFin-F^p6%F`pFj_v/FjsF[t@$3-FM6#F`ev4Fc
[wC)>87-&Fhgq6#%'chooseGFd^t>F[tF_`m>FinF_`m?&FisF\]wF\wC&>8C-Fban6$.&F^gq6#&Fi
sF`r/Fg[tFbar>8BF\w?&8DF`evF_^w@$-FB6$*&Ff]wF`oFa^wFcoFbio>F_^wF%@$F_^wC$>Fin6$
FinFis>F[t6$F[tFh[w>Fin7#Fin-F^p6%F`pFj_v/%0computed~cones~GFinFb\w@$3-FM6#Fhdv
Fi\wC)>F\]wF]]w>F[tF_`m>FinF_`m?&FisF\]wF\wC+-F^p6&"")Fj_vFis/%,checked~at~GF^`
v>8=Fj[w>8;-&Fjr6#%(adjointG6#Fc`w>89-F[emFj`w@$/F\awF:\>8<-Fdu6$Fe`w7#-Fcq6$&F
hdvF[^wFdhv>8>F\w?&8?-Fbeo6$<#-Ffbn6#Fabv<#-F]alFjtFjaw@$1&Fhdv6#F\bw*&-&Fjr6#%
*innerprodG6$Fbaw-&Fjr6#%$rowG6$F]qF\bwF`o-%%signG6#F\awF`o>FjawF%@$FjawC$>FinF
j^w>F[t6$F[tF\aw>FinF^_wF__wFb\w-F^p6%FegoFj_v/%Gcomputed~topdimensional~cones~
at~time~GF^`v-F^p6%FegoFj_v/%Jstart~computing~Stanley-Reisner~ideal~at~GF^`v@$4
Fg\wC(>85F_`m>84-&Fhgq6#%(subsetsG6#F_bw>86Fjco?(F$F`oF`oF$31-Fgp6#FbewFgr4&F[e
w6#.%)finishedGC'>Fbew-&F[ew6#%*nextvalueGF$>8:F\w?&F\do7#FidwFdfw@$/-Fbeo6$F\d
oFbewFjco>FdfwF%?&88FinFdfw@$/-Fbeo6$Fbew<#-F]al6#F]gwFjco>FdfwF%@$Fdfw>Fidw6$F
idwFbew>FidwFffw>F`ev7#-Fcq6$-Fban6$.&F^gq6#&&FidwF`]tF`r/Fg[t;F`o-Fgp6#Fdhw/Ff
eo;F`o-Fgp6#Fidw>F^o-Fhdm6#-Fifl6$FjgvF`ev-F^p6%F`pFj_v/.F^oF^o>FDF]`l>FjarFin>
&FD6#%&dets_G7#F[t>&FD6#%,edgevalues_GF^^r>F[cr-F]anF]]q>F\imF]gl>F[arF^gq>&FD6
#%0StanleyReisner_GF`ev>FjnFgr>FcblF_[w>F[cl7#-Ffbn6$F`oF]ju>FcclF^o>&FD6#%(smo
oth_G-%&evalbG6#/-%$absG6#-Fau6$F\jw%"*GF`o@$4Fa[x-F\_u6#%4Variety~is~singularG
>Ff]w-Fi[x6#&F[tFdx>FfeoF`o?(FarF`oF`oFfoF\w@$2-Fi[x6#&F[tF`rFf]wC$>Ff]wF[]x>Ff
eoFar>Fjcl-Fhdm6#*&-Fban6$.&F^^r6#&&FinF`]tF`rF]^wF`o-Fi[x6#&F[tF`]tFco@$0-Fgdo
6$Fjbv<%F\flFiel.%$intGFjcoC%-F^p6%FegoFj_v/%Cstart~computing~monomialvalues~at
~GF^`vFfn-F^p6%F`pFj_v/%Bstop~computing~monomialvalues~at~GF^`v@$0-Fgdo6$Fjbv<$
F\flFielFjcoC&-F^p6%FegoFj_v/%Cstart~computing~additive~bases~at~GF^`vF^fl-F^p6
%F`pFj_v/%Bstop~computing~additive~bases~at~GF^`v-F^p6%FegoFj_v/%3Betti~numbers
~are~G-F_jlFT@$0-Fgdo6$Fjbv<$F\flF^dlFjcoC%-F^p6%FegoFj_v/%Bstart~computing~tan
gentbundle~at~GF^`v>Fadl,&FgrF`o-Fc[l6$-Fc[l6$*()&F^^rF`rFfeoF`o)F\\lFfeoF`o-F[
joF`]tFco/FfeoFbar/FarFabvF`o-F^p6%F`pFj_v/%Astop~computing~tangentbundle~at~GF
^`v-F^p6%FegoFj_v/%2exit~toricvarietyGF^`vF_flF$F$F$%$EndGf*FggoF$F$F$C$@$F8-F<
6#%.usage:~End(A)G-Faim6$FDFDF$F$F$F[inf*6%FbjlF^^nF*F^cnF$F$C%@$F8-F<6#%Vusage
:~bundle(rank,name)~or~bundle(rank,name,variety)G@%Fhhl>FinF[^m>FinF\^l,&FDF`o-
Fadn6$,&F`oF`o-Fc[l6$*&-Fcp6$FganFgrF`oFidnF`o/FgrFgfnF`oFinF`oF$F$F$Fgnf*F)6;%
%MONSGF^ip%"RGFi^l%#rdG%&relsdG%(monvarsGF]_vFeal%$dsbGFgbm%$mlsG%#ttG%#ptG%$eq
sGF``rFagrFh`oFbfm%#rnGF2F3Fg[oFh[oF1F$F$C5@$F8-F<6#%9usage:~monomialvalues(X)G
-F^p6%"#:Fap%5enter~monomialvaluesG>FisFjn>FghqFcbl>F[ewFccl>FidwFfiv>Fbew-Fgp6
#F[ew>F[t-Fcq6$/&FghqFdgw*&)F`^r&F[clFdgwF`oF_fxF`o/F]gw;F`oFidw>Fgr-FS6$FDFis>
Fin-FgpF_\m-F^p6%F`pFap%?start~collecting~all~relationsG>F]qF_`m?(F\]wF`oF`oFbe
wF\wC&>F^o-Fhdm6#&F[ew6#F\]w>Ffo-%'degreeG6$-Fifl6$F[tF^oF`^r@$1FfoFisC$>F\do&F
O6#,&FisF`oFfoFco?(F]gwF`oF`o-FgpFhiuF\w>F]q6$F]q-Fhdm6#*&F^oF`o&F\doFdgwF`o-F^
p6%FbexFap-Fcp6%%1relation~number~GF\]w%'~done.G>F]q<#F]q>Fjo-FgpF]]q-F^p6%Fego
Fap-Fcp6&%,#relations=GFjo%.,~#monomials=GFin@%/FjoF:@%/FinF`o>&FY6#&FgrFdxF`o-
FG6#%=no~relations~in~top~degree??GC)>F^gqF_`m?(F\]wF`oF`oFjoF\wC%>Fe`w7#-Fd\o6
%&F]qFdgxFghq.Fdfw>Fdfw7#Fdfw>F^gq6$F^gq-Fedn6$*&&Fe`w6#.F]gwF`o&Fbaw6#&FdfwFg[
yF`o/Fh[y;F`o-Fgp6#Fe`w>F^r<#-Fcq6$&Fbaw6#&FgrFdgw/F]gwFhar-F^p6%F`pFap-Fcp6$%F
start~solving~linear~equations,~time=GFb_v>Far-F\hv6$<#F^gqF^r-F^p6%F`pFap-Fcp6
$%Ifinished~solving~linear~equations,~time=GFb_v?&FfeoFgrF\w>&FYF`]t-Fifl6$Far&
FbawF`]t@%4F[ir-F\_u6#%Xintegrals~only~computed~up~to~a~common~(unknown)~scalar
GC'-F^p6%F`pFap%<normalize~so~that~[point]=1G>Fe`w7#-Fd\o6%FjclFcblF^[y>FdfwF`[
y>F^^r-Fc[l6$*&&Fe`wFecwF`o&FY6#&FdfwFecwF`o/F\awF]\y?&FfeoFgrF\w>Fh]y*&Fh]yF`o
F^^rFco-Fcp6%%:computed~integral~of~all~GFin%9~monomials~of~top~degreeGF$F$F$%'
koszulGf*FggoF[]mF$F$C$@$F8-F<6#%1usage:~koszul(A)G-Fc[l6$*&)FcoFgrF`o-Fdas6$Fg
rFDF`o/Fgr;F:F_cmF$F$F$FjfpFd[o%&curveGf*6%%"CGF[_lFe^pF$F$F$C-@$F8-F<6#%4usage
:~curve(C,g,p)G>FDF]`l>FjnF`o>FcblFa_s>F[clFc_s>FjclFg]m>Fccl7#*$Fg]mFjv>Fadl,&
F`oF`o*(,&FjvF`oF]glFedmF`oFg]mF`oF\\lF`oF`oFhgpF^flF`^lF$F$F$%&POINTG=F$F%E\[l
,F[[lF`oFen=F$F%E\[l"F`oF`oFcdlF:F_u=F$F%E\[l"F:Fc_sFeclF[ilF]clF[ilF\dlF`oF`t=
F$F%E\[l"F:Fc_sF\oF:FQ=F$F%E\[l"F:Fc_sFeblF[il%.schurfunctor2Gf*6$%#muGF16$F3F.
FieqF$C$@$F8-F<6#%Busage:~schurfunctor2(partition,A)G@'/-FgpFTF:F`o/FecyF`o-Fg_
u6$-F]alFTF]gl-Fhdm6#-Fc[l6$*&)FcoF^_sF`o-Ffjm6$-Fg_u6$,(&FDF^[lF`oFinFcoF`oF`o
F]gl-Fiby6$7$-Fcq6$,&&FDF_\mF`oF`oF`o/Fgr;F`oF^_s-Fcq6$F\ey/Fgr;F_auFecyF]glF`o
/Fin;F`oFecyF$F$F$%/productvarietyGf*6'%"WGF*Fi\m%$pr1G%$pr2G6,%#dxG%#dyGFgbm%#
mmGF2F3F.Fg^lFi^l%#dbGF$F$C-@$F8-F<6#%hnusage:~productvariety(W,X,Y)~or~product
variety(W,X,Y,pr1,pr2)G>FgrFj]m>FinF[^m>FD-FE6#7%/F\o,&FgrF`oFinF`o/Febl7$F^cu-
F]alFa_m/F]cl7$Fdcu-F]al6#&Fg]mF\cl@$3-FM6#&F]glFZ-FM6#&Fg]mFZC$FR?&F^o&&F]glFP
F_\mF\w?&Ffo&&Fg]mFPF^[lF\w>&FY6#*&F^oF`oFfoF`o*&&FigyFhoF`o&F\hyFhpF`o@$3-FM6#
F^du-FM6#&Fg]mF[dl>Fjcl*&F^duF`oFaiyF`o@$3-FM6#F^eu-FM6#&Fg]mFbdl>Fadl,&F^euF`o
FjiyF`o@$3-FM6#Fgiu-FM6#&Fg]mF_t?(FisF:F`oF\gyF\wC'>FarF_`m>F[tF_`m?(Fjo-Fhhp6$
F:,&FisF`oFgrFcoF`o-Fc`u6$FisFinF\wC$>Far6$Far-Fcq6$-Fcq6$-Fhdm6#*&&&Fgiu6#,&Fi
sF`oFjoFcoF]]qF`o&&FcjyF[qF]rF`o/F]q;F`o-Fgp6#Fi[z/F^r;F`o-Fgp6#F]\z>F[t6$F[t-F
cq6$-Fcq6$-Fhdm6#*&&&Fa[v6#,(FgrF`oFisFcoFjoF`oF]]qF`o&&&Fg]mF^u6#,&FinF`oFjoFc
oF]rF`oF^\zFb\z>&F^tFjt7#Far>&F]u6#,(FgrF`oFinF`oFisFcoF\jw@$F`atC&-Ff\m6%Fc^mF
DF]gl-Ff\m6%9(FDFg]m>&Fc^mFdy%)product_G>&Fe^zFdyFh^zF_flF`^lF$F$F$Faimf*F``pF$
F$F$C$@$F8-F<6#%0usage:~Hom(A,B)G-Ffjm6$-F\hl6#F`^pF]glF$F$F$%*integral2Gf*F$Fg
\sF$F$C%@$F8-F<6#%Dusage:~integral2(X,c),~integral2(c)G@&F[fpC$>FgrFbx>FinFfxFh
xC$>FgrF[y>FinFbx-Fhdm6#*&-Fe\s6$FgrFinF`o-Fe\s6$FgrFa[qFcoF$F$F$FSf*6%F*%#a1G%
#a2G6)FbjlF[_l%%genfGF``r%%degsGF.%'resultGF$F$C'@$F8-F<6#%jnusage:~monomials(X
)~or~monomials(X,n)~or~monomials(n,vars,degs)G@$-FB6$F]fp7%FjalFdvFdvC*>FgrFD>F
foF]gl>FjoFg]m>F^o-Fban6$*$,&F`oF`o*&F^`qF`o)F\\l&FjoF]]qF`oFcoFco/F]qFer>F^o-F
hdm6#-Fau6$-Fhho6%F^oF\\lFcboFbio>F^o-Fg[l6%F^oF\\lFgr@%-FB6$F^oFbbq>F^r7#-F]al
Fho>F^r7#F^o-F<F]r@'-FB6$F]fp7$FEFjal>Fgr-Fhhp6$F]glFjn-FB6$F]fp7#FE>FgrFjn-FG6
#%Xusage:~monomials(variety)~or~monomials(variety,integer)G@$4-FM6#&FOF_\mC(>Ff
oFcbl>FjoF[cl-F^p6%F`pFap%Fstarting~to~build~generating~functionG>F^oF`bz>F^oFi
bz?(F]qF:F`oFgrF\wC$>Fin-Fg[l6%F^oF\\lF]q@%-FB6$FinFbbq>&FOF]]q7#-F]alF^[l>F_fz
F^_w@%F_x&FOFccmFOF$F$F$%$&^*GFa^pFi^of*6$Fi\mFc^p6$F2FgdxF$F$C$@$F8-F<6#%8usag
e:~codimension(Y,y)G-Fggx6$-Fifl6$-Fcq6$/&FcblF_\m*&FegzF`o)Fin&F[clF_\mF`o/Fgr
;F`o-FgpFahmF]glFinF$F$F$F^hmf*6$Fi^lF*F$F$F$C$@$F8-F<6#%6usage:~o(d)~or~o(d,X)
G@'F_x-F\cn6%F`o7#FDF]glFhx-F\cn6$F`oFfhz-FG6#%Jusage:~o(d)~or~o(d,X),~d=class,
~X=varietyGF$F$F$F`[lf*F$6'F*Fh^lFh[oFg[oF3F$F$C)@$F8-F<6#%Dusage:~integral(c)~
or~integral(X,c)G@'F_xC$>FgrFbx>FinFfxFhxC$>FgrF[y>FinFbxF]y@$5/&FgrFdyFfy/F]jz
Fhy-F<6#-F`[l6$&FgrF\z-Fjfp6$&FgrFbzFin@$4-FM6#&FgrFZ-F<6#.-9!F]hl>F^o7#-Fd\o6%
-FhdmF^[lFgjp.Ffo>Ffo7#Ffo-Fc[l6$*&F_dpF`o-Fiq6$F[[[l&FfoF[qF`o/Fjo;F`o-FgpFhoF
$F$F$F$,
I$DIMF:F$,
I)version_%&0.999GF$
