M7R0
I#SF=6"%&falseGE\[l:%'varsetG-%(readlibG6$%*SF/varsetG%MC:\Users\Jan\Desktop\sc
hubertlib/SF/varset.mG%*conjugateG-F)6$%-SF/conjugateG%PC:\Users\Jan\Desktop\sc
hubertlib/SF/conjugate.mG%&hooksG-F)6$%)SF/hooksG%LC:\Users\Jan\Desktop\schuber
tlib/SF/hooks.mG%*jt_matrixG-F)6$%-SF/jt_matrixG%PC:\Users\Jan\Desktop\schubert
lib/SF/jt_matrix.mG%(nextParG-F)6$%+SF/nextParG%NC:\Users\Jan\Desktop\schubertl
ib/SF/nextPar.mG%$tosG-F)6$%'SF/tosG%JC:\Users\Jan\Desktop\schubertlib/SF/tos.m
G%*add_basisG-F)6$%-SF/add_basisG%PC:\Users\Jan\Desktop\schubertlib/SF/add_basi
s.mG%$zeeG-F)6$%'SF/zeeG%JC:\Users\Jan\Desktop\schubertlib/SF/zee.mG%$toeG-F)6$
%'SF/toeG%JC:\Users\Jan\Desktop\schubertlib/SF/toe.mG%(char2sfG-F)6$%+SF/char2s
fG%NC:\Users\Jan\Desktop\schubertlib/SF/char2sf.mG%'evalsfG-F)6$%*SF/evalsfG%MC
:\Users\Jan\Desktop\schubertlib/SF/evalsf.mG%'subParG-F)6$%*SF/subParG%MC:\User
s\Jan\Desktop\schubertlib/SF/subPar.mG%)plethysmG-F)6$%,SF/plethysmG%OC:\Users
\Jan\Desktop\schubertlib/SF/plethysm.mG%&stdegG-F)6$%)SF/stdegG%LC:\Users\Jan\D
esktop\schubertlib/SF/stdeg.mG%)dominateG-F)6$%,SF/dominateG%OC:\Users\Jan\Desk
top\schubertlib/SF/dominate.mG%%skewG-F)6$%(SF/skewG%KC:\Users\Jan\Desktop\schu
bertlib/SF/skew.mG%(sf2charG-F)6$%+SF/sf2charG%NC:\Users\Jan\Desktop\schubertli
b/SF/sf2char.mG%'scalarG-F)6$%*SF/scalarG%MC:\Users\Jan\Desktop\schubertlib/SF/
scalar.mG%+dual_basisG-F)6$%.SF/dual_basisG%QC:\Users\Jan\Desktop\schubertlib/S
F/dual_basis.mG%$ParG-F)6$%'SF/ParG%JC:\Users\Jan\Desktop\schubertlib/SF/Par.mG
%&thetaG-F)6$%)SF/thetaG%LC:\Users\Jan\Desktop\schubertlib/SF/theta.mG%$tohG-F)
6$%'SF/tohG%JC:\Users\Jan\Desktop\schubertlib/SF/toh.mG%$topG-F)6$%'SF/topG%JC:
\Users\Jan\Desktop\schubertlib/SF/top.mG%(itensorG-F)6$%+SF/itensorG%NC:\Users
\Jan\Desktop\schubertlib/SF/itensor.mG%&omegaG-F)6$%)SF/omegaG%LC:\Users\Jan\De
sktop\schubertlib/SF/omega.mGF$,
I)SF/Bases<&%"eG%"hG%"pG&%"sGF$F$,
I.SF/homog_cmps-F)6$-%&evalnG6#Ffs%QC:\Users\Jan\Desktop\schubertlib/SF/homog_c
mps.mGF$,
I*SF/to_ehp-F)6$-Fjs6#F]t%MC:\Users\Jan\Desktop\schubertlib/SF/to_ehp.mGF$,
I*SF/jt_det-F)6$-Fjs6#Fct%MC:\Users\Jan\Desktop\schubertlib/SF/jt_det.mGF$,
I+SF/getrows-F)6$-Fjs6#Fit%LC:\Users\Jan\Desktop\schubertlib/SF/tools.mGF$,
I+SF/getbase-F)6$-Fjs6#F_uF^uF$,
I)SF/shape-F)6$-Fjs6#FduF^uF$,
I)SF/bytes-F)6$-Fjs6#FiuF^uF$,
I*SF/normal-F)6$-Fjs6#F^vF^uF$,
I)SF/added-F)6$-Fjs6#Fcv%LC:\Users\Jan\Desktop\schubertlib/SF/added.mGF$,
I+SF/dualize-F)6$-Fjs6#Fiv%NC:\Users\Jan\Desktop\schubertlib/SF/dualize.mGF$,
I*SF/verify-F)6$-Fjs6#F_w%MC:\Users\Jan\Desktop\schubertlib/SF/verify.mGF$,
I)SF/apply-F)6$-Fjs6#FewFdwF$
