M7R0
I)SF/addedf*6%%"bG%#spG%#f0G6$%"fG%#muG6"F+C$@%2""#9#>8$-%%subsG6$<#-%$seqG6$/&
9$6#-%#opG6#8%&-%,SF/added/gsG6$F<-&%#SFG6#.%*conjugateGF@6#F//FA9%9&>F2&-FD6$F
<FNFL-F46$-%$mapG6$f*6#%"xGF+6$%)operatorG%&arrowGF+&-%0SF/added/etableG6#F<6#"
""F+F+F+-&FH6#.%'varsetG6$F2&%"eGF+F2F+F+F+F+,
I,SF/added/gsf*6$F%F*6*%"gG%#lcGF)F'%#scG%#nuG%"NG%"cG6#%)rememberGF+C*>FA-&%*S
F/lcoeffGF\o6#-FG6#FN>8&*&FAF^o&Ffo6#-F?FjpF^o>F2&-F[oFjpFL>8(7">8)-F46$/""!%%N
ULLG7#-%(convertG6$FN%"+G>8**&FAF/-&FH6#.%'scalarG6'F2F2F\rF\r&%)SF/iprodGF\oF^
o?(F+F^oF^oF+0FhqFNC$@$5&%*SF/nondomGF\o-&FH6#.%)dominateG6$FhqFNC+>8+&-F[o6#Fh
qFL>F]t-%'normalG6#-Fgr6'F2F]tF\rF\rF\s>Feq7$-F?6#Feq/&Ffo6#-F?F`tF]t>8'-FD6$F<
Fhq>F]t-Fct6#*(FAF^o&F`uF]o!""-F46$Feq&F`uFLF^o>F\q,&F\qF^o*&F]tF^oF[vF^oFhu@$2
"&++#-%'lengthG6#F\q>F\q-%(collectG6&F\q-FW6$f*FZF+FfnF+-F?6$F^oF<F+F+F+Feq.%,d
istributedGFct>Fdr,&FdrF^o*&F]tF/FguF^oFhu@$2"%+5-Fcv6#Fdr>Fdr-FctFgw>Fhq-&FH6#
.%(nextParGF`t7$-%'factorGFgw-Fgv6&F\q-FW6$f*FZF+FfnF+F\wF+F+F+FeqF^wFctF+F+F+F
+,
I0SF/added/etablef*6#F*6(%"vGF[p%#tfG%%varsG%"jG%"dGFapF+C'>F2-F`r6$7#-F86$-%$c
atG6$.FfoFeq/FeqF<%"*G>Fhq-F?6$F^o7$-F?F\oF\r>F`u7#-F86$-Fiy6$.%"pGFeq/Feq;F^oF
hq>FA-%'coeffsG6%-&FH6#.%$topG6$F2F[zF`u.F\q7$/&Ffo6#FbzF27%7#FA7#F\qFhqF+F+F+F
+
