M7R0
I*SF/scalarf*6"6,%"fG%"gG%#tfG%#ipG%"bG%"dG%"uG%#muG%"jG%$resGF$F$C*@%5/9#""$/F
4""&>8'&9"6#F4>F9&%#SFG6#.%$zeeG@%2F5F4>8(7#&F;6#;F5""%C$>&FF6#"""%%NULLG>&FF6#
""#FQ>8$7#-%$seqG6$-%0SF/scalar/parseG6$&F;6#8,&FFFjn/F[o;FPFU>8-""!>8)-%$minG6
$&&FWFO6#F5&&FWFTFio@%1-%%nopsG6#&FhoFT-F_p6#&F[pFTC%>8%-%$zipG6%f*6$%"xG%"yGF$
6$%)operatorG%&arrowGF$7$9$9%F$F$F$&FhoFOFap>8&Fdp>FW&F[pFOC%>Fgp-Fip6%f*F\qF$F
_qF$FbqF$F$F$FiqFdp>FgqFap>FWFeq?&8*Fgp%%trueG@$-%'memberG6%&FbrFTFgq.F[oC$>8+-
%)SF/shapeG6%Fhr.%"pGFco>F`o,&F`oFP*(-F96#F\sFP&FbrFOFP&FWFjnFPFPF`oF$F$F$F$,
I0SF/scalar/parsef*6$F&F*6&F'%"iGF+%$tmsGF$F$C&@$32FPF4/FdqFao-%'RETURNG6#Fcq>F
W-&F?6#.%$topG6#F;>Fgq-&F?6#.%'varsetG6$FWF`s7%7#-%'coeffsG6%FW7#-FZ6$-%$catG6$
F`sFgp/Fgp;FPFgq.F97#F9FgqF$F$F$F$
