M7R0
I*SF/varsetf*6#%"fG6*%%indsG%%strsG%)one_baseG%"bG%"vG%$resG%"iG%'digitsG6"F/C-
>8$<">8%F3>8)-%&tableGF/>8&%&falseG@%/9#""">8'%)SF/BasesG>FB&9"6#""#@$-%%typeG6
$FB.%%nameGC$>F;%%trueG>FB<#FB?&8(FBFQ@%-FK6$FU.%(indexedGC$>F2<$-%#opG6#F2-Fin
6$""!FU>&F76#F[o%%NULLGC$>F5<$-Fin6#F5FU>&F76#FUF]o@$2F]o-%%nopsGFfo>8+-F96#7#-
%$seqG6$/-%$catG6#8*Fjp/Fjp;F]o""*?&FU-%'indetsG6$9$FMFQ@%FWC$>FBF[o@$-%'member
G6$FBF2>&F76#FB6$F[r7#-FinFioC$>FB-%*substringG6$FU;F@F@@$-Fhq6$FBF5>F[r-%$maxG
6$F[r-%.SF/varset/degG6$FUF_p?&FBF2FQ>F[r7#F[r@%F;&F76$FeoFhn-Fin6#F7F/F/F/F/,
I.SF/varset/degf*6$F+F.6%F-%"jG%"nGF/F/C%>F;F]o?(F2FHF@-%'lengthG6#FbqFQC%>F5-F
cr6$Fbq;F2F2@$4-%)assignedG6#&9%Ffo-%'RETURNG6#F]o>F;,&F;"#5F^uF@F;F/F/F/F/
