M7R0
I6schubert/blowuppointsf*6%%"XG%"kG%"eG6'%"iG%"jG%"rG%"vG%%relsG6"F.C/@$/9#""!-
%'RETURNG6#%;usage:~blowuppoints(X,k,e)G>-%$catG6$.%"BG9&-%&tableGF.>&F96#%+dim
ension_G&9$FC>&F96#%+variables_G7$-%#opG6#&FFFI-F:6$.F>;"""9%>&F96#%)degrees_G7
$-FM6#&FFFX-%$seqG6$FT/8$FS@$-%)assignedG6#&FF6#%'point_G>&F9FboFao>&F96#%0mono
mialvalues_G-%%copyG6#&FFFho-%+setvarietyG6#F9?(F\oFTFTFU%%trueG>&Fgo6#)-F:6$FR
F\o%$DIMG)!"",&FipFTFTFT@$3-F_o6#&FF6#%+relations_GF^oC%>8(7$-FMF`q-Fin6$,&FfpF
T*&)F[qFipFTFeoFTFTF[o?&8'FOFbp?(8%FTFTFUFbp>Ffq7$-FM6#Ffq*&F_rFT-F:6$FRFarFT?(
F\oFTFT,&FUFTF[qFTFbp?(Far,&F\oFTFTFTFTFUFbp>Ffq7$Fdr*&FgpFTFgrFT@$-F_o6#&FF6#%
/tangentbundle_GC%>&F9FbqFfq>8&-%"oG6#-%$addG6$FgpF[o>&F9Fds,*FcsFT*&FEFT,&FTFT
-%%dualG6#FjsF[qFTF[qFjsFTF[qFT-%)morphismG6%-F:6$.%"pGF>F9FF-%&whereGF.F.F.F.F
.
