M7R0
I.schubert/exppf*6"6(%"pG%"cG%"iG%"kG%#AAG%$dimGF$F$C+-%)userinfoG6%"#5%%exppG%
+enter~exppG@'/9#""">8)%$DIMG/F5""#@%-%%typeG6$&9"6#F;%(integerG>F8F@-%&ERRORG6
#%<second~argument~not~integerG-FF6#%Ischubert/expp~must~have~1~or~2~argumentsG
>8$-%&arrayG6#;""!F8>8%FN>8(-%'expandG6#&FA6#F6?(8'F6F6F8%%trueG>&FM6#Fgn*()!""
FgnF6-%*factorialGF[oF6-%&coeffG6%FV%"tGFgnF6>&FT6#FRF6?(FgnF6F6F8FhnC$>&FTF[o-
%/schubert/stripG6#,$*&-%$sumG6$*&&FT6#,&FgnF68&F^oF6&FM6#FhpF6/Fhp;F6FgnF6FgnF
^oF^o-F.6%F0F1-%$catG6$%-done~degree~GFgn-Fbp6$*&&FTFjpF6)FdoFhpF6/FhpFQF$F$F$F
$
