M7R0
I/schubert/Grassf*6'%"fG%"kG%"AG%"cG%$strG6/%$lowG%$ltmG%#ssG%#tmG%#sbG%"rG%"nG
%"iG%"jG%"dG%#PPG%#MMG%#stG6"F8C=@$/9#""!-%'RETURNG6#%Ousage:~Grass(f,k,A,c)~or
~Grass(f,k,A,c,option)G>9$-%&tableGF8>8)-%%rankG6#9&@$529%F=2FGFO-%&ERRORG6#%6G
rassmannian~is~emptyG>&FC6#%'arank_GFG>&FC6#%'qrank_GFO>&FC6#%.vectorbundle_GFK
>&FC6#%+dimension_G*&FO""",&FGF`oFO!""F`o>&FC6#%/basedimension_G%$DIMG>&FC6#%&n
ame_G9'>&FC6#%+variables_G7#-%$catG6$.F\p;F`oFO>&FC6#%)degrees_G7#-%"$G6#Ffp>&F
C6#%)section_G)-Fcp6$FepFOFao>&FC6#%&kind_G%1grassmannbundle_G>&FC6#%/upperstar
data_G%%NULLG>8&-%&segreG6%F`oFgoFK>8(6$-%$seqG6$/-Fcp6$.%"hG8+&Far6#F`s/F`s;F`
oFgo-Fir6$/F\sF=/F`s;,&FgoF`oF`oF`o,&FgoF`oF_oF`o>F`s.F`s-%*monomialsG6#FC?(8*F
=F`oFgo%%trueGC)-%)userinfoG6%"#5%&debugG-Fcp6$%6starting~codimension~G,&FgoF`o
FbtFbo>8'-%3schubert/tosmatrixG6$,&FbtF`oF_oF`oFO>8.-%'SF/ParGFbu>8$-&%'linalgG
6#.%'vectorG6#-%%nopsG6#Feu?(8,F`oF`oFavFct>&Fiu6#Fev-%%subsG6$Ffr-&F\v6#%$detG
6#-%-SF/jt_matrixG6%&FeuFhv7#-F]q6$FaoFOF^s>8%-&F\v6#.%)multiplyG6$F_uFiu?(FevF
`oF`oFavFctC%>8--Fbv6#Fdw>&8/Fhv*&-%(productG6$.)-Fcp6$FepF`s,&&FdwFbsF`o&Fdw6#
,&F`sF`oF`oF`oFbo/F`s;F`o,&FcxF`oFboF`oF`o)-Fcp6$FepFcx&Fdw6#FcxF`o>&&FC6#%+low
erstar_G6#Fgx&FiwFhv-Fft6%FhtFit%;lowerstar~computation~doneG>Fgo,&F\oF`oFdoF`o
>-Fcp6$.%"QGF\p-%'bundleG6$FOF\p>&FC6#%0quotientbundle_GF[[l@$/F<""&C$>80-%*sub
stringG6$&9"6#Fh[l;F`o""$@$5/F[\l.%$tanG/F[\l.%$allGC$-Fft6%FhtFit%5start~tange
nt~bundleG-%.tangentbundleGF`t-Fft6%Fht%&whereG-Fcp6&%4currentvariety_~is~G%0cu
rrentvariety_G%*,~DIM~is~GFgoFCF86#FgoF8F8
