M7R0
I4schubert/insertedgef*6(%"YG%"XG%"xG%"vG%"aG%"bG6.%"nG%"dG%"iG%"jG%#ycG%$yedG%
%bigcG%&scsetG%%coneG%(compsetG%#ccG%#scG6"F8C2@$/9#""!-%'RETURNG6#%Zusage:~ins
ertedge(Y,X,x,v)~or~insertedge(Y,X,x,v,options)G>8$-%%nopsG6#&9%6#%/edgevariabl
es_G>8%&FH6#%+dimension_G>8)-&%'linalgG6#%'matrixG6$,&FC"""FYFYFL?(8&FYFYFC%%tr
ueG?(8'FYFYFLFfn>&FQ6$FenFhn&&FH6#%'edges_GF[o?(FhnFYFYFLFfn>&FQ6$FXFhn&9'6#Fhn
>8(-%(convertG6$&FH6#%'cones_G%$setG>8*<">8/-%*whichconeG6$FHFeo>8+-Fjo6$FdpF_p
?&8,FhoFfn@$/-%*intersectG6$-Fjo6$F]qF_pFipFip>Fap-%&unionG6$Fap<#F]q>Fho-%&min
usG6$FhoFap>8-Fbp?&8.FapFfn>F_r-Fgq6$F_r<#-F\r6$-Fjo6$FarF_pFip?&FenFdpFfn?&Fhn
F_rFfn>Fho-Fgq6$Fho<#7%-%#opGFfo-Fbs6#-F\r6$Fip<#FenFX-%-toricvarietyG6'9$7$-Fb
sFF9&FQ-Fjo6$Fho%%listG&9"6#;""&F<F8F8F8F8
