M7R0
I8schubert/monomialvaluesf*6#%"XG6;%%MONSG%"NG%"RG%"dG%#rdG%&relsdG%(monvarsG%$
solG%$dimG%$dsbG%"mG%$mlsG%#ttG%#ptG%$eqsG%%varsG%%relsG%"vG%"rG%#rnG%"iG%"jG%$
monG%$cofG%"AG6"F@C5@$/9#""!-%'RETURNG6#%9usage:~monomialvalues(X)G-%)userinfoG
6%"#:%&debugG%5enter~monomialvaluesG>8,&9$6#%+dimension_G>83&FS6#%+variables_G>
84&FS6#%+relations_G>85-%%nopsG6#FW>86-F]o6#Ffn>8--%$seqG6$/&FW6#88*&)80&&FS6#%
)degrees_GFjo"""FioFcp/F[p;FcpF[o>8$-%*monomialsG6$FSFQ>8%-F]o6#Fgp-FK6%"#5FN%?
start~collecting~all~relationsG>8)%%NULLG?(87FcpFcpF`o%%trueGC&>8&-%'expandG6#&
Ffn6#Fgq>8'-%'degreeG6$-%%subsG6$FdoF[rF^p@$1FbrFQC$>8/&&FS6#%+monomials_G6#,&F
QFcpFbr!""?(F[pFcpFcp-F]o6#F]sFhq>Fdq6$Fdq-F]r6#*&F[rFcp&F]sFjoFcp-FK6%FMFN-%$c
atG6%%1relation~number~GFgq%'~done.G>Fdq<#Fdq>8(-F]o6#Fdq-FK6%""&FN-Fat6&%,#rel
ations=GFht%.,~#monomials=GF\q@%/FhtFE@%/F\qFcp>&&FS6#%0monomialvalues_G6#&Fgp6
#FcpFcp-%&ERRORG6#%=no~relations~in~top~degree??GC)>82Feq?(FgqFcpFcpFhtFhqC%>8;
7#-%'coeffsG6%&FdqF`rFW.8:>F_w7#F_w>Fdv6$Fdv-%$sumG6$*&&Fhv6#.F[pFcp&8<6#&F_wFi
wFcp/Fjw;Fcp-F]o6#Fhv>8*<#-Ffo6$&F\x6#&FgpFjo/F[p;FcpF\q-FK6%FaqFN-Fat6$%Fstart
~solving~linear~equations,~time=G-%%timeGF@>8+-%&solveG6$<#FdvFdx-FK6%FaqFN-Fat
6$%Ifinished~solving~linear~equations,~time=GFby?&8.FgpFhq>&Fhu6#F`z-Fgr6$Fey&F
\xFcz@%4-%)assignedG6#&FS6#%'point_G-%&printG6#%Xintegrals~only~computed~up~to~
a~common~(unknown)~scalarGC'-FK6%FaqFN%<normalize~so~that~[point]=1G>Fhv7#-F[w6
%F\[lFXF^w>F_wFaw>81-%$addG6$*&&Fhv6#89Fcp&Fhu6#&F_wFc\lFcp/Fd\lF`x?&F`zFgpFhq>
Fbz*&FbzFcpF]\lFds-Fat6%%:computed~integral~of~all~GF\q%9~monomials~of~top~degr
eeGF@F@F@F@
