M7R0
I6schubert/toricvarietyf*6%'%"XG%%nameG%"xG%&edgesG6H%"dG%&conesG%%relsG%"nG%#v
vG%#edG%#lrG%"iG%"pG%%detsG%"jG%#mcG%#spG%%varsG%#vxG%%specG%"SG%#SRG%"cG%%cand
G%#ccG%#ddG%(inidealG%$inmG%#lfG%$matG%&pconeG%"qG%$timG%&ampleG%&infanG%"mG%"r
G%&optioG%$opsG%$solG%$strG%%sridG6"FQCS>8@-%%timeGFQ@$/9#""!-%'RETURNG6#%Gusag
e:~toricvariety(X,x,edges,options)G-%)userinfoG6%""&.%&toricG/%<enter~toricvari
ety~at~time~G,&FU"""FT!""@'-%%typeG6$9&-%%listG6#-Fjo6#%(integerG>8)-&%'linalgG
6#%'matrixG6#Fho-Ffo6$FhoFep>F`p-%%evalGFfp-%&ERRORG6#%Sthird~argument~must~be~
a~matrix~or~a~list~of~listsG>8$-&Fcp6#%'coldimG6#F`p>8'-&Fcp6#%'rowdimGFfq@'-Ff
o6$9%Fjo>82F`r-Ffo6$F`rF'>Fbr7#-%$catG6$.F`r;FboFhq-F]q6#%Nsecond~argument~must
~be~name~or~list~of~namesG-Fjn6%"#5F]o/%3edgevariables~are~GFbr>8F<"?&8E7#&9"6#
;""%FY%%trueG@/-Ffo6$Fhs%)equationGC$>8H-%*substringG6$-%$lhsG6#Fhs;Fbo""$@*5/F
ft.%$PicG/Fft.%$picG>83-%$rhsGF\u/Fft.%$ampG>8AFiu/Fft.%$conG>8%Fiu/Fft.%$sriG>
8IFiu-Ffo6$FhsF\p>F_vFhs-Ffo6$FhsFio>FdvFhs-Ffo6$Fhs-Fjo6#%(polynomG>FivFhs-Ffo
6$Fhs-Fjo6#Fct>FhuFhs-Ffo6$Fhs%'symbolG>Fes-%&unionG6$Fes<#-Fht6$FhsF]u-F]q6#/%
?argument~not~of~correct~type:~GFhs>8(-Fbp6%FboFhqFbr>8*-&Fcp6#%)multiplyG6$Fjx
F`p@$4-%)assignedG6#Fhu>Fhu7">8G-%&solveG6$<$-%#opGFhy-%$seqG6$&F^y6$Fbo8+/Fhz;
FboFaq<#-Fbz6#Fbr@$/F\z%%NULLG-F]q6#%Egiven~elements~of~Pic~are~dependent!G>806
$-Fdz6$-F[u6#&Fhu6#Fhz/Fhz;Fbo-%%nopsGFhy-Fbz6#-%$mapG6$F[u-%'selectG6$f*6#%#eq
GFQ6$%)operatorG%&arrowGFQ/-F[u6#9$-FjuFa]lFQFQFQF\z>81-%%subsG6$-Fbz6#F\zFbr-F
jn6&FasF]o/%+Pic~basis~G7#Fe[l/%)at~time~GFao@$-Fgy6#FdvC$>8--Fdz6$-&Fcp6#%$det
G6#-&Fcp6#%*submatrixG6%F`p7#-Fbz6#&8,6#FjzFjz/Fh_lFdv-Fjn6%FasF]o/.Fg^lFg^l@$3
-Fgy6#Fiv4Fc^lC)>87-&%)combinatG6#%'chooseG6$FhqFaq>Fg^lF`[l>FdvF`[l?&Fh_lFf`lF
_tC&>8C-%(productG6$.&Fbr6#&Fh_lF\\l/.FhzFjz>8BF_t?&8DFivF]bl@$-Ffo6$*&FbalFboF
_blFcoFdw>F]bl%&falseG@$F]blC$>Fdv6$FdvFh_l>Fg^l6$Fg^lFj^l>Fdv7#Fdv-Fjn6%FasF]o
/%0computed~cones~GFdvF[`l@$3-Fgy6#F_vFc`lC)>Ff`lFg`l>Fg^lF`[l>FdvF`[l?&Fh_lFf`
lF_tC+-Fjn6&"")F]oFh_l/%,checked~at~GFao>8=F__l>8;-&Fcp6#%(adjointG6#Fbdl>89-F[
_lFidl@$/F[elFZ\>8<-F`y6$Fddl7#-Fdz6$&F_vFhalFiz>8>F_t?&8?-%&minusG6$<#-%"$G6#F
[s<#-Fbz6#Fh_lFiel@$1&F_v6#F[fl*&-&Fcp6#%*innerprodG6$Fael-&Fcp6#%$rowG6$F`pF[f
lFbo-%%signG6#F[elFbo>FielFebl@$FielC$>FdvFibl>Fg^l6$Fg^lF[el>FdvF]clF^clF[`l-F
jn6%F\oF]o/%Gcomputed~topdimensional~cones~at~time~GFao-Fjn6%F\oF]o/%Jstart~com
puting~Stanley-Reisner~ideal~at~GFao@$4Fa`lC(>85F`[l>84-&Fi`l6#%(subsetsG6#F_fl
>86Ffs?(FQFboFboFQ31-F`\l6#FdilFaq4&F]il6#.%)finishedGC'>Fdil-&F]il6#%*nextvalu
eGFQ>8:F_t?&8/7#F[ilFfjl@$/-F]fl6$FhjlFdilFfs>FfjlFebl?&88FdvFfjl@$/-F]fl6$Fdil
<#-Fbz6#F`[mFfs>FfjlFebl@$Ffjl>F[il6$F[ilFdil>F[ilFijl>Fiv7#-Fdz6$-Fdal6$.&Fbr6
#&&F[il6#8.F\\l/F[bl;Fbo-F`\l6#Fg\m/Fi\m;Fbo-F`\l6#F[il>8&-%'expandG6#-Fg]l6$F
\zFiv-Fjn6%FasF]o/.Fc]mFc]m>Fb]l-%&tableGFQ>&Fb]l6#%'cones_GFdv>&Fb]l6#%&dets_G
7#Fg^l>&Fb]l6#%,edgevalues_GFe]l>&Fb]l6#%'edges_G-F[qFfq>&Fb]l6#%&name_GF`r>&Fb
]l6#%/edgevariables_GFbr>&Fb]l6#%0StanleyReisner_GFiv>&Fb]l6#%+dimension_GFaq>&
Fb]l6#%+variables_GF_^l>&Fb]l6#%)degrees_G7#-Fafl6$Fbo,&FhqFboFaqFco>&Fb]l6#%+r
elations_GFc]m>&Fb]l6#%(smooth_G-%&evalbG6#/-%$absG6#-%(convertG6$Fh^m%"*GFbo@$
4Fcam-%&printG6#%4Variety~is~singularG>Fbal-F[bm6#&Fg^l6#Fbo>Fi\mFbo?(FhzFboFbo
FhqF_t@$2-F[bm6#&Fg^lF\\lFbalC$>FbalF`cm>Fi\mFhz>&Fb]l6#%'point_G-Fe]m6#*&-Fdal
6$.&Fe]l6#&&FdvFh\mF\\lFjalFbo-F[bm6#&Fg^lFh\mFco@$0-%*intersectG6$Fes<%.%$allG
.%$basG.%$intGFfsC%-Fjn6%F\oF]o/%Cstart~computing~monomialvalues~at~GFao-%/mono
mialvaluesGFa]l-Fjn6%FasF]o/%Bstop~computing~monomialvalues~at~GFao@$0-Fjdm6$Fe
s<$F]emF_emFfsC&-Fjn6%F\oF]o/%Cstart~computing~additive~bases~at~GFao-%.additiv
ebasisGFa]l-Fjn6%FasF]o/%Bstop~computing~additive~bases~at~GFao-Fjn6%F\oF]o/%3B
etti~numbers~are~G-%&bettiGFa]l@$0-Fjdm6$Fes<$F]em.%$tanGFfsC%-Fjn6%F\oF]o/%Bst
art~computing~tangentbundle~at~GFao>&Fb]l6#%/tangentbundle_G,&FaqFbo-%$addG6$-F
fhm6$*()&Fe]lF\\lFi\mFbo)%"tGFi\mFbo-%*factorialGFh\mFco/Fi\mFjz/FhzF[sFbo-Fjn6
%FasF]o/%Astop~computing~tangentbundle~at~GFao-Fjn6%F\oF]o/%2exit~toricvarietyG
Fao-%+setvarietyGFa]lFQFQFQFQ
