M7R0
I4schubert/totalspacef*6%%"fG%"XG%$strG6.%"iG%$dimG%$DimG%"dG%#bbG%$dbbG%$matG%
#stG%"cG%"rG%"jG%"kG6"F5C&@$/9#""!-%'RETURNG6#%Qusage:~totalspace(f,X)~or~total
space(f,X,option)G>-%$catG6$.%"TG9$-%&tableGF5@$5/&FE6#%&kind_G%1grassmannbundl
e_G/FK%2projectivebundle_GC/>8%&9%6#%+dimension_G>8&&FEFV>&F@FV,&FS"""FYFhn>&F@
6#%-basevariety_GFU>&F@6#%+variables_G7$-%#opG6#&FEF_o-Fco6#&FUF_o>&F@6#%)degre
es_G7$-Fco6#&FEF[p-Fco6#&FUF[p>&F@FLFK>&F@6#%3structuremorphism_GFE>&F@6#%'poin
t_G*&&FUF\qFhn&FE6#%)section_GFhn>&FE6#%(source_GF@>&FE6#%(target_GFU-%+setvari
etyG6#F@@$/F9""$C%>8+-%*substringG6$9&;FhnF`r@$5/Fcr.%$allG/Fcr.%$tanGC$>&F@6#%
/tangentbundle_G,&&FEFdsFhn&FUFdsFhn>&F@6#%+toddclass_G-%%toddG6#Fcs@$5F[s/Fcr.
%$basGC(-%)userinfoG6%"#5%&debugG%<start~generating~dual~basesG@&FOC$>8,Fbo>&FE
6#%'fiber_G-FG6#7'/FWFY/F`o7#F_u/F\p7#Fhn/%+relations_G7#)F_u,&FYFhnFhnFhn/F]q)
F_uFYFJC(>F_u&FE6#%&name_G>8-&FE6#%'arank_G>8/&FE6#%'qrank_G-%&grassG6%F^wFivF_
u>-FA6%.%"QGF_uFE-FA6$FhwF_u>Fau-FA6$.%"GGF_u-%.additivebasisG6#FauF[r@$FJ>Fjw-
%'bundleG6$F^wF_u?(8'F:FhnFgn%%trueGC)>8(%%NULLG>8)F_y?(8$-%$maxG6$F:,&FjxFhnFY
!""Fhn-%$minG6$FjxFSF[yC$>F^y6$F^y-%$seqG6$-F`z6$-%'expandG6#*&&&&FU6#%'basis_G
6#Fcy6#F^wFhn&&&FauF[[l6#,&FjxFhnFcyFhy6#8.Fhn/Fe[l;Fhn-%%nopsG6#F`[l/F^w;Fhn-F
i[l6#Fiz>Fay6$Fay-F`z6$-F`z6$-Fez6#*&&&&FU6#%+dualbasis_G6#,&FSFhnFcyFhyF^[lFhn
&&&FauF[]l6#,(FYFhnFjxFhyFcyFhnFd[lFhnFf[lF[\l>&&F@F[[l6#Fjx7#F^y>8*-%$mapG6$%)
integralG-&%'linalgG6#.%)multiplyG6$-%&arrayG6#Fh]l-&Fa^l6#.%*transposeG6#-Fg^l
6#7#Fay>Fj]l-Fj^l6#-&Fa^l6#.%(inverseG6#Fj]l>&&F@F[]l6#,(FSFhnFYFhnFjxFhy-%(con
vertG6$-F`^l6$Fj]lF__l%%listG-%&whereGF5F5F5F5F5
