M7R0
I3schubert/whichconef*6$%"XG%"vG6.%"dG%"nG%"iG%*smallconeG%%coneG%(conesetG%%su
bmG%%colsG%#vvG%%varsG%#eqG%$lhsG6"F4C)@$/9#""!-%'RETURNG6#%6usage:~whichcone(X
,v)G>8%-%%nopsG6#&9$6#%/edgevariables_G>8$&FD6#%+dimension_G>8+7#-%$seqG6$8&/FR
;"""FH>8'<#-FP6$FR/FR;FUF??&8(&FD6#%'cones_G%%trueGC$>8)-%(convertG6$Fhn%$setG@
$4/-%*intersectG6$F_oFW<"C&>8*-&%'linalgG6#%*submatrixG6%&FD6#%'edges_GFhnFM>8-
-&F`p6#%'matrixG6%FUFH7#-FP6$-%$catG6$.8,FRFS>8/-%&evalmG6#-&F`p6#%)multiplyG6$
FhpF]p@$-&%(simplexG6#%)feasibleG6$<#-FP6$/&Fgq6$FUFR&9%6#FRFS%,NONNEGATIVEG>FW
-Fho6$FWF_o-Fao6$FW%%listGF4F4F4F4
